---
version: 2.1

orbs:
  terraform: feedyard/terraform@0.1.0

on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/

workflows:
  version: 2
  lab-platform-vpc-pipeline:

    jobs:
      - plan-cluster-vpc:
          name: sandbox-change-plan
          workspace: sandbox
          filters: *on-push-master

      # - terraform/plan:
      #     name: sandbox-change-plan
      #     context: ZTW
      #     shell: secrethub run -- /bin/sh -eo pipefail
      #     workspace: sandbox
      #     before-terraform:
      #       - run:
      #           name: template environmental configuration and credentials
      #           command: |
      #             secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
      #             secrethub inject -i tpl/sandbox.auto.tfvars.json.tpl -o sandbox.auto.tfvars.json
      #     filters: *on-push-master

      - approve-sandbox-changes:
          type: approval
          requires:
            - sandbox-change-plan
          filters: *on-push-master

      - apply-cluster-vpc:
          name: sandbox-change-apply
          workspace: sandbox
          account: nonprod
          filters: *on-push-master

      # - terraform/apply:
      #     name: sandbox-change-apply
      #     context: ZTW
      #     shell: secrethub run -- /bin/sh -eo pipefail
      #     workspace: sandbox
      #     before-terraform:
      #       - run:
      #           name: setup credentials from secrets
      #           command: |
      #             secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
      #             secrethub inject -i tpl/sandbox.auto.tfvars.json.tpl -o sandbox.auto.tfvars.json
      #             secrethub inject -i tpl/nonprod.test.sh.tpl -o nonprod.test.sh
      #     after-terraform:
      #       - run:
      #           name: test sandbox account changes
      #           environment:
      #             TEST_ENV: sandbox
      #           command: secrethub run -- bash nonprod.test.sh sandbox
      #     requires:
      #       - approve-sandbox-changes
      #     filters: *on-push-master

      # git tag = plan prod-role changes
      - terraform/plan:
          name: prod-change-plan
          context: ZTW
          shell: secrethub run --env-file secrethub.prod.env -- /bin/sh -eo pipefail
          workspace: prod
          working-directory: roles
          before-terraform:
            - run:
                name: setup credentials from secrets
                command: |
                  secrethub inject -i tpl/subaccount.auto.tfvars.json.tpl -o roles/subaccount.auto.tfvars.json
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
          filters: *on-tag-master


jobs:
  
  plan-cluster-vpc:
    
    parameters:
      workspace:
        description: terraform workspace (infrastructure environment) name
        type: string
        default: ""

    steps:
      - terraform/plan:
          context: ZTW
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: << parameters.workspace >>
          before-terraform:
            - run:
                name: template plan << parameters.workspace >>
                command: |
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/<< parameters.workspace >>.auto.tfvars.json.tpl -o << parameters.workspace >>.auto.tfvars.json

  apply-cluster-vpc:

    parameters:
      workspace:
        description: terraform workspace (infrastructure environment) name
        type: string
        default: ""
      
      account:
        description: aws account target
        type: string
        default: ""

    steps:
      - terraform/apply:
          context: ZTW
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: << parameters.workspace >>
          before-terraform:
            - run:
                name: setup credentials from secrets
                command: |
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/<< parameters.workspace >>.auto.tfvars.json.tpl -o << parameters.workspace >>.auto.tfvars.json
                  secrethub inject -i tpl/<< parameters.account >>.test.sh.tpl -o << parameters.account >>.test.sh
          after-terraform:
            - run:
                name: test changes
                environment:
                  TEST_ENV: << parameters.workspace >>
                command: secrethub run -- bash << parameters.account >>.test.sh << parameters.workspace >>
